import { useEffect, useState } from "react";
import Layout from "./components/Layout";

const allWords = [
  "Aberration",
  "Abstain",
  "Acidic",
  "Acrimony",
  "Actuate",
  "Adept",
  "Advocate",
  "Affable",
  "Affinity",
  "Affirm",
  "Allege",
  "Allocate",
  "Aloof",
  "Amalgam",
  "Ambiguous",
  "Ambivalent",
  "Amenable",
  "Amorphous",
  "Animosity",
  "Anomalous",
  "Anticipate",
  "Antipathy",
  "Apathy",
  "Appease",
  "Apprehension",
  "Approve",
  "Arbitrator",
  "Archaic",
  "Arduous",
  "Artful",
  "Attain",
  "Audacious",
  "Augment",
  "Auspicious",
  "Austere",
  "Aver",
  "Baffle",
  "Belie",
  "Belittle",
  "Bellicose",
  "Benefactor",
  "Besiege",
  "Betray",
  "Blockade",
  "Broadcast",
  "Buttress",
  "Callous",
  "Calumny",
  "Candid",
  "Canoe",
  "Censure",
  "Chaotic",
  "Charitable",
  "Chastise",
  "Circumspect",
  "Clarify",
  "Colossal",
  "Commend",
  "Commensurate",
  "Commiserate",
  "Comply",
  "Concede",
  "Conceptualize",
  "Condemnation",
  "Condense",
  "Conform",
  "Confront",
  "Congenial",
  "Conniving",
  "Conspicuous",
  "Construct",
  "Contempt",
  "Corporeal",
  "Corroborate",
  "Counteract",
  "Crate",
  "Credential",
  "Culminate",
  "Culpable",
  "Curb",
  "Curtail",
  "Decline",
  "Decode",
  "Defend",
  "Definitive",
  "Degenerative",
  "Delectable",
  "Deliberate",
  "Demeanour",
  "Demur",
  "Denigrate",
  "Denounce",
  "Deprive",
  "Deride",
  "Despicable",
  "Deter",
  "Detrimental",
  "Devolve",
  "Diligent",
  "Discomfit",
  "Discourse",
  "Discredit",
  "Disdainful",
  "Disguise",
  "Disgusting",
  "Disintegrate",
  "Dismay",
  "Disparage",
  "Dispute",
  "Distinction",
  "Durability",
  "Dynamic",
  "Edible",
  "Efficacy",
  "Egregious",
  "Elation",
  "Eliminate",
  "Elucidate",
  "Embolden",
  "Emulate",
  "Endorsement",
  "Endowment",
  "Enervate",
  "Enhance",
  "Enlarge",
  "Enumerate",
  "Epitomize",
  "Equivocal",
  "Eradicate",
  "Eschew",
  "Ethereal",
  "Exhilaration",
  "Expose",
  "Expropriation",
  "Extant",
  "Extensive",
  "Extraneous",
  "Fervent",
  "Fluster",
  "Forthright",
  "Fortitude",
  "Frenetic",
  "Frugal",
  "Fruitful",
  "Fulminate",
  "Gainsay",
  "Galvanize",
  "Gauge",
  "Generosity",
  "Germane",
  "Glib",
  "Glut",
  "Gorgeous",
  "Gregarious",
  "Guile",
  "Harangue",
  "Hardened",
  "Hedge",
  "Humiliate",
  "Humorous",
  "Iconoclast",
  "Illegible",
  "Illegitimate",
  "Immerse",
  "Impair",
  "Impertinent",
  "Implicate",
  "Impress",
  "Impudent",
  "Incarceration",
  "Incomprehensible",
  "Inconsequential",
  "Incorrigible",
  "Indefatigable",
  "Indefensible",
  "Indelible",
  "Indictment",
  "Indigent",
  "Indulgent",
  "Inexplicable",
  "Initiate",
  "Innate",
  "Innocuous",
  "Insidious",
  "Instill",
  "Insubordination",
  "Integrity",
  "Intimate",
  "Intrepid",
  "Intricate",
  "Introspect",
  "Intuitive",
  "Inveterate",
  "Invincible",
  "Involved",
  "Irrelevant",
  "Laconic",
  "Latent",
  "Laudable",
  "Lax",
  "Leisure",
  "Levitate",
  "Licentious",
  "Loquacious",
  "Magnanimous",
  "Maintain",
  "Malaise",
  "Malign",
  "Malleable",
  "Mast",
  "Menial",
  "Mercurial",
  "Meticulous",
  "Metrics",
  "Misanthrope",
  "Misery",
  "Misgiving",
  "Mitigate",
  "Modest",
  "Mollify",
  "Mortal",
  "Mount",
  "Nostalgic",
  "Novice",
  "Obscure",
  "Ocular",
  "Ominous",
  "Omnipotent",
  "Optimal",
  "Ostentatious",
  "Overpower",
  "Parochial",
  "Parsimonious",
  "Peculiarities",
  "Penal",
  "Penchant",
  "Perilous",
  "Persistent",
  "Personas",
  "Personify",
  "Perspire",
  "Persuade",
  "Pessimistic",
  "Placate",
  "Poignant",
  "Precursor",
  "Predator",
  "Predilection",
  "President",
  "Prevail",
  "Prevalent",
  "Prevaricate",
  "Proclaim",
  "Prodigal",
  "Professed",
  "Proficient",
  "Profligate",
  "Progressive",
  "Prolong",
  "Propensity",
  "Protract",
  "Prudence",
  "Prurient",
  "Qualify",
  "Querulous",
  "Rabid",
  "Realign",
  "Recalcitrant",
  "Reckless",
  "Reclusive",
  "Reconcile",
  "Regressive",
  "Reparation",
  "Rescind",
  "Resent",
  "Resilient",
  "Resist",
  "Resolution",
  "Restate",
  "Restive",
  "Restrictive",
  "Retrace",
  "Retrospect",
  "Revoke",
  "Rival",
  "Riveting",
  "Robust",
  "Rouse",
  "Salient",
  "Sanguine",
  "Secretive",
  "Semantic",
  "Sequel",
  "Sluggish",
  "Stagnant",
  "Stagnation",
  "Steely",
  "Sterile",
  "Stigmatize",
  "Strain",
  "Stringent",
  "Subservient",
  "Supercilious",
  "Supplant",
  "Surmount",
  "Surreptitiously",
  "Tactile",
  "Temper",
  "Temperamental",
  "Tepid",
  "Terse",
  "Timorous",
  "Tormenting",
  "Torpor",
  "Triumph",
  "Ubiquitous",
  "Unconstrained",
  "Undermine",
  "Undeterred",
  "Undignified",
  "Unmasked",
  "Upbraid",
  "Vacillate",
  "Vehement",
  "Venality",
  "Venerate",
  "Vengeance",
  "Veracious",
  "Vicarious",
  "Vindicate",
  "Virulent",
  "Wary",
  "Waver",
  "Word",
  "Wrench",
];

function App() {
  const [words, setWords] = useState(allWords);

  const [index, setIndex] = useState(Math.floor(Math.random() * words.length));

  useEffect(() => {
    setIndex(Math.floor(Math.random() * words.length));
  }, [words]);

  const removeWord = () => {
    const currentWord = words[index];
    const newWords = words.filter((word) => word !== currentWord);
    setWords(newWords);
  };

  const getNextIndex = () => {
    setIndex(Math.floor(Math.random() * words.length));
  };
  return (
    // <Container maxWidth="md">
    //   <h1>Worderize</h1>
    //   {!words.length ? (
    //     <h2>Congrtatulations. You memorized all the words.</h2>
    //   ) : (
    //     <>
    //       <h2>{words[index]}</h2>
    //       <button onClick={removeWord}>Know</button>
    //       <button onClick={getNextIndex}>Don't Know</button>
    //       <br />
    //     </>
    //   )}
    //   <button onClick={() => setWords(allWords)}>Reset</button>
    //   <h3>Total : {allWords.length}</h3>
    //   <h3>Remaining : {words.length}</h3>
    //   <h3>Current Index : {index}</h3>
    // </Container>
    <Layout />
  );
}

export default App;
